# AMIGAAAAA
SET(CMAKE_SYSTEM_NAME Amiga)

SET(CMAKE_FIND_ROOT_PATH  ${AMIGA_TOOLCHAIN_PATH})
# specify the cross compiler
SET(CMAKE_C_COMPILER   "${AMIGA_TOOLCHAIN_PATH}/bin/m68k-amigaos-gcc")
SET(CMAKE_ASM-VASM_COMPILER "${AMIGA_TOOLCHAIN_PATH}/bin/vasmm68k_mot")
SET(CMAKE_CXX_COMPILER "${AMIGA_TOOLCHAIN_PATH}/bin/m68k-amigaos-g++")

SET(CMAKE_C_FLAGS "-noixemul -m68040" CACHE STRING "" FORCE)
SET(CMAKE_CXX_FLAGS "-noixemul -m68040" CACHE STRING "" FORCE)

SET(UNIX false)
SET(AMIGA true)